package com.ziplly.app.client.view.factory;

public enum ValueFamilyType {
	BASIC_DATA_VALUE,
	ACCOUNT_NOTIFICATION,
	ACCOUNT_INFORMATION,
	PERSONAL_ACCOUNT_INFORMATION,
	BUSINESS_ACCOUNT_INFORMATION,
	PRIVACY_SETTINGS,
	ACCOUNT_NOTIFICATION_SETTINGS,
}
