package com.ziplly.app.client.view.factory;

public enum ValueType {
	// General
	STRING_VALUE,
	DATE_VALUE,
	DATE_VALUE_SHORT,
	INTEGER_VALUE,
	DATE_VALUE_MEDIUM,
	
	// Account Notification
	RECIPIENT_ACCOUNT_NOTIFICATION_VALUE,
	ANNOUNCEMENT_NOTIFICATION_VALUE,
	ACCOUNT_NOTIFICATION_SENDER_IMAGE,
	
	// Account
	EMAIL_VALUE,
	NAME_VALUE,
	TIME_CREATED_VALUE,
	TINY_IMAGE_VALUE,
	SMALL_IMAGE_VALUE,
	MEDIUM_IMAGE_VALUE,
	LARGE_IMAGE_VALUE,
	
	// Personal Account
	PERSON_NAME_VALUE,
	PERSON_IMAGE_VALUE,
	
	// Business Account
	BUSINESS_NAME_VALUE,
	BUSINESS_IMAGE_VALUE,
	BUSINESS_ADDRESS_VALUE, 
}
